### PR TITLE
Imagescan Rebuild: 2021-09-12

### PR DESCRIPTION
**Pull request by dislbenn**
Rebuilding imagescan for open-cluster-management/search-operator repo.

### CODE REVIEW

**Comment by dislbenn** [comment]
Rebuild for the issue: https://github.com/open-cluster-management/backlog/issues/15862

**Review by SherinV — APPROVED** [review]

**Comment by SherinV** [comment]
Merging since 
1. all other jobs except e2e is working
2. This is only a readme update

**Comment by SherinV** [comment]
For https://github.com/open-cluster-management/backlog/issues/15862

**Pull request merged**
