### PR TITLE
dummy update for base image rebuild

### PR DESCRIPTION
**Pull request by SherinV**
For https://github.com/open-cluster-management/backlog/issues/11044

### CODE REVIEW

**Comment by jlpadilla** [comment]
This won't fix the image vulnerability. Check the quay.io image scan here: https://quay.io/repository/open-cluster-management/search-operator?tab=tags

image

**Comment by SherinV** [comment]
@jlpadilla Thanks, Passed after I added the microdnf update. Do we need to update downstream too?

**Comment by jlpadilla** [comment]
I don't know if we are currently using `microdnf update` in the downstream images.  There has been conflicting guidance, the last I saw as of last week was to not do the update and wait for the base image to get updated.
Downstream is easier to trigger a rebuild of all the images, so it's less painful than upstream.

**Pull request merged**
